In [350]:
# importing libraries
import pandas as py
import matplotlib.pyplot as plt
import numpy as np

In [351]:
# importing the dataset
dataset = py.read_csv('kc_house_data.csv')

In [352]:
dataset

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [353]:
# getting information on the dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

In [354]:
dataset['price'].corr(dataset['id']) # checking correlation among various variable

-0.016762196614445116

In [355]:
dataset['price'].corr(dataset['zipcode'])    # checking correlation among various variable

-0.053202854298325664

In [356]:
dataset['price'].corr(dataset['sqft_lot15'])   # checking correlation among various variable

0.08244715251948591

In [357]:
# removing those columns which have very less correlaton with price
dataset= dataset.drop(['id','date','zipcode','sqft_lot15'],axis=1)

In [358]:
dataset.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'lat', 'long',
       'sqft_living15'],
      dtype='object')

In [359]:
X=dataset.iloc[:,1:].values #variable that are used for predicting
y=dataset.iloc[:,0].values#variable that we are using to prict the value (Price)

In [360]:
print(X)

[[ 3.00e+00  1.00e+00  1.18e+03 ...  4.75e+01 -1.22e+02  1.34e+03]
 [ 3.00e+00  2.25e+00  2.57e+03 ...  4.77e+01 -1.22e+02  1.69e+03]
 [ 2.00e+00  1.00e+00  7.70e+02 ...  4.77e+01 -1.22e+02  2.72e+03]
 ...
 [ 2.00e+00  7.50e-01  1.02e+03 ...  4.76e+01 -1.22e+02  1.02e+03]
 [ 3.00e+00  2.50e+00  1.60e+03 ...  4.75e+01 -1.22e+02  1.41e+03]
 [ 2.00e+00  7.50e-01  1.02e+03 ...  4.76e+01 -1.22e+02  1.02e+03]]


In [361]:
print(y)

[221900. 538000. 180000. ... 402101. 400000. 325000.]


In [362]:
#splitting datset into two set i.e. training nd testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=1/3, random_state=0)

In [363]:
len(X_train)

14408

In [364]:
len(X_test)

7205

In [365]:
len(y_train)

14408

In [366]:
len(y_train)

14408

In [367]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [368]:
# creating a predictor
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 288000.  297000.]
 [1800000. 1578000.]
 [ 600000.  562100.]
 ...
 [ 548050.  592500.]
 [ 275000.  284900.]
 [ 340000.  380000.]]


In [369]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.744133974732771